### ISSUE TITLE
Error occurred when using "Swipe" diff type to show the changes

### ISSUE THREAD

**Issue by elinaw123** [koordinates/kart-qgis-plugin#110]
**Describe the bug**
An error occurred when using "Swipe" diff type to show the changes under the "Geometries" tab.

**To Reproduce**
1. Import a point layer from PostGIS 
2. Add one extra point
3. Select "Show working copy changes for this dataset..."

**Expected behavior**
I expected to see the before and after changes in a split window.

**Screenshots**
<img width="782" alt="image" src="https://github.com/koordinates/kart-qgis-plugin/assets/173649817/c2c694f4-d504-48ac-ac60-4997e185de9e">

**Version info (this is important!):**
Kart Plugin version
1.0.14
QGIS version
3.34.6-Prizren
Operating system
Windows 11 10.0.22631 SP0
Kart version
Kart v0.15.2, Copyright (c) Kart Contributors
» GDAL v3.8.5; PROJ v9.4.0; PDAL v2.6.0
» PyGit2 v1.12.1; Libgit2 v1.6.4; Git v2.45.1.7.g5be46a8262; Git LFS v3.3.0
» SQLAlchemy v1.4.45; pysqlite3 v2.6.0/v3.45.3; SpatiaLite v5.1.0; Libpq v16.0.2

**Comment by jakimowb** [comment]
I can reproduce the bug (appeared during workshop on QGIS UC 2024)

**Comment by hamishcampbell** [comment]
Thanks!
