### ISSUE TITLE
Github Setup for bug reporting & contributing

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#15]
- [x] Issue template — make sure we're getting the right info/OS/versions/logs/context/etc to help figure issues out quickly.
- [x] Contributing doc — how to get up and running with the plugin for development (as opposed to "install from here"), conventions, etc.

**Comment by volaya** [comment]
I added the contributing doc, taking inspiration from the corresponding one in Kart.
I have also configured the CI to produce artifacts for each commit, with a valid zip file that can be installed using the QGIS plugin manager. The version is automatically set to `dev-[GIT_SHA]`

About the issue tempate, I do not have permissions to edit that, but I guess the most important info will be plugin version, kart version, qgis version, and a stack trace if possible. Any suggestion on how to make it easier for the user to collect that info from the plugin?

**Comment by rcoup** [comment]
> Any suggestion on how to make it easier for the user to collect that info from the plugin?

I think easiest is probably a Plugins...Kart...About dialog showing version info we need with copy & paste-able text.

I don't know how logging is normally done in QGIS plugins, but maybe we create/truncate a plugin log file each QGIS session and then have the About dialog link to it so people can find it to attach to a bug report?

**Comment by volaya** [comment]
Ok, I will add that menu entry. That's what I have thought as well. 

Logging goes to the QGIS log, where users can copy & paste easily. In case of an unhandled exception, QGIS will show a full error trace that can also be copied. That's the usual way for reporting bugs in plugins.

**Comment by volaya** [comment]
@rcoup Here is what is shown now in the About menu of the plugin:

![image](https://user-images.githubusercontent.com/2101651/136008641-2eca8239-5712-4409-84c6-e2a1aeb7ff51.png)

In case Kart is not correctly installed and configured, a warning message is shown in the Kart details section. It also adds the current configuration of the kart folder in the plugin

**Comment by rcoup** [comment]
Looks good to me, we can expand as we need to.

**Comment by rcoup** [comment]
@volaya can we add the Operating System name & version to the About Kart dialog? Easier for a user to copy & paste.

**Comment by volaya** [comment]
Done
