### ISSUE TITLE
Support spatial filters

### ISSUE THREAD

**Issue by volaya** [koordinates/kart-qgis-plugin#3]

**Comment by rcoup** [comment]
Essentials:

Currently in Kart spatial filters only affect the working copy, not the data transferred over the network. But that will be a future expansion with the same user interface.

* `kart checkout --spatial-filter=<FILTER>` sets or changes a spatial filter
* `kart clone --spatial-filter=<FILTER>` does it at clone-time — clone is just a shortcut for fetch+createworkingcopy+checkout
* `kart checkout --spatial-filter=""` clears it
* `kart config kart.spatialfilter.geometry` & `kart config kart.spatialfilter.crs` to retrieve the current filter
