### ISSUE TITLE
UI minor changes rollup

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#35]
Minor UI changes (mostly wording) rollup issue

- [x] Working tree → Working copy everywhere

![CleanShot 2021-11-23 at 10 57 33](https://user-images.githubusercontent.com/59874/143013221-629e648a-aca2-43f3-80d6-b72a8670aece.png)
- [x] heading → “Your Kart installation location is not configured:”
- [x] stray "."

![CleanShot 2021-11-23 at 10 52 40](https://user-images.githubusercontent.com/59874/143014558-d9a5bf86-4ce2-42fa-9cd3-1142848a6fdf.png)
- [x] pane titlebar → "Kart Repositories"
- [x] hint text → "Tip: right-click on items for available actions"
- [x] remove logo/heading (~ideally move logo to pane title~ not a thing)
- [x] add a space between repo title & branch name
- [x] can we collapse the repository path in the middle when the panel isn't wide enough and the repo doesn't have a title set? I think Qt supports this via [elidedText](https://doc.qt.io/qt-5/qfontmetrics.html#elidedText). ie:

      /Users/rcoup/code/kart-foss4g-2021/workshop/first [mybranch]  # now
      ~/code/kart-foss4g-2021/workshop/first [mybranch]             # use ~ for os.path.expanduser('~') prefix
      ~/code/.../workshop/first [mybranch]                          # collapse in the middle

![CleanShot 2021-11-23 at 11 25 21](https://user-images.githubusercontent.com/59874/143016099-646328f5-1447-4ec3-88a1-6543d204112b.png)

- [x] Remove this repository: icon → `minus-circle-outline`
- [x] Show log: icon → `history`
- [x] Show working tree changes: icon → `compare`
- [x] Discard working tree changes: icon → `undo`
- [x] Commit working tree changes: icon → `content-save-outline`
- [x] Switch branch: icon → `swap-horizontal`
- [x] Apply patch: icon → `file-import-outline`
- [x] Menu order/wording
  - -break-
  - Show log...
  - Show working **copy** changes...
  - Discard working **copy** changes
  - Commit working **copy** changes...
  - Switch branch...
  - Merge into **{current-branch}**...
  - -break-
  - Pull...
  - Push...
  - -break-
  - Import layer **to repository**...
  - Apply patch...
  - -break-
  - Refresh
  - Properties...
  - Remove this repository

![CleanShot 2021-11-23 at 12 02 17](https://user-images.githubusercontent.com/59874/143020869-2da04ab7-3934-470d-bfb9-c384dcc333a2.png)

- [x] Matching icon and wording changes from the repository context menu
- [x] Menu ordering:
  - Add to QGIS project
  - -break-
  - Show log...
  - Show working **copy** changes for dataset...
  - Discard working **copy** changes for dataset
  - Commit working **copy** changes for dataset...
  - -break-
  - Remove from repository

Diff Viewer dialog
- [x] **Restore** old version
- [x] **Restore** new version
- [x] Don't show restore new version when displaying working-tree changes
- [x] Project layers should be the default for "additional layers"
- [x] Map extent needs some padding so vertices don't end up drawn on the edges of the map
- [x] Swipe cursor should change from hand to resize when the mouse hovers over the black line
- [x] ~Scrolling to zoom seems really rough~ nevermind, is my machine
- [x] [status message] Working copy has been **updated**.

Layer context menu
- [x] ~Can we add the Kart icon to make it stand out a bit in the menu?~
- [x] Wording/icons need to match the other menus

**Comment by volaya** [comment]
The QGIS API does not allow adding icons to the group entry in the layer context menu

**Comment by rcoup** [comment]
Looking good! A few more

- [ ] Can we auto-expand Repositories in the explorer pane if we have some?
- [ ] And ideally auto-expand Datasets when you expand a repository
- [ ] I think we should drop the entire logo & heading from here... it still looks awkward to me. 

  ![CleanShot 2021-12-14 at 11 57 04](https://user-images.githubusercontent.com/59874/145994303-6b5d3f02-83d7-4243-a0b9-4d62b3971362.png)

**Comment by volaya** [comment]
We can have the content autoexpand. The reason for expanding it on demand is that populating the tree requires calling kart, so if you have several repos, that would mean several calls to get metadata information (layers, current branch, etc) for each of them, which can take time.

Maybe we can have that as an option, so the user can select what to do. For users with a couple of repos, it is a good thing, but if there are many, users migh want to disable that behaviour

I will take away the logo and heading, no problem.

**Comment by rcoup** [comment]
> The reason for expanding it on demand is that populating the tree requires calling kart, so if you have several repos, that would mean several calls to get metadata information (layers, current branch, etc) for each of them, which can take time.

Good point.

> Maybe we can have that as an option, so the user can select what to do. For users with a couple of repos, it is a good thing, but if there are many, users migh want to disable that behaviour

I'm not a huge fan of infinite options. How about just expanding the last-used/opened repository?

**Comment by volaya** [comment]
Yes, that can be a solution. However, to expand the first level ("Repositories"), we already need to make one call for each repo, in order to get the name of the current branch for each repo, to show it along with its name)
Maybe we can change that to not show the current branch (I think it's quite useful), or to show it in a different place, under the repo item, so we do not need to get the current branch name just to show the repo name.
