### ISSUE TITLE
CRS issue with diff

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#37]
Working with the foss4g workshop first repo
- add the building-points-topo layer to the map
- edit a non-geometry attribute of a couple of features
- right click on the building-points-topo repo dataset and select _Show working tree changes for this dataset..._
- I get a CRS selector popup, with the context "Specify CRS for layer vertexdiff"
- select 4326 (which is the dataset CRS in the repo) then ok
- select a different feature; get the same CRS selector popup again
- see the attribute diff
- go to _Geometries_, see nothing (regardless of what you do in the CRS selector)
- select _Swipe_ diff type, get an error popup:
```
Traceback (most recent call last):
  File "/Users/rcoup/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/kart/gui/swipemap.py", line 52, in paint
    image = self.image.copy(0, 0, int(w), int(h))
AttributeError: 'NoneType' object has no attribute 'copy'
```
- stuck in a loop, eventually esc+clicking lots QGIS crashes with a segfault

**Comment by volaya** [comment]
This should be fixed now

**Comment by rcoup** [comment]
The error popup/crash is fixed, but the CRS-selector popups are still happening.

**Comment by volaya** [comment]
mmm, it can, and actually I added a change that, in case there is no CRS in the dataset, it should not ask you for it, yo the CRS dialog should not appear in any case.
