### ISSUE TITLE
Highlight shallow clones/grafts in commit logs

### ISSUE THREAD

**Issue by rcoup** [koordinates/kart-qgis-plugin#44]
If a user does a shallow clone, it would be good if the commit log highlighted that are more commits not shown. We can tell such a commit using the `grafted` tag. Not sure what's easiest — adding another row to the table with a message? Maybe something like "This repository is a shallow clone, history past this point is not available locally"?

/cc @hamishcampbell

**Comment by volaya** [comment]
Using the "grafted" ref, I added this

![image](https://user-images.githubusercontent.com/2101651/145028279-8b8884cb-a113-45b2-b627-587415f4a8d8.png)

**Comment by volaya** [comment]
Two questions:

-The clone functionality of the plugin does not allow creating shallow clones. Should we add it?
- If so, the clone command does not allow shallow cloning for local repos, unless the file:// prefix is added. Considering we have removed that, we might need to think about how to implement the shallow cloned.

Feel free to close this issue if the solution in the history dialog is ok, and open a new one for the shallow clone functionality

**Comment by rcoup** [comment]
I think what you have is good for now. 👍 

> The clone functionality of the plugin does not allow creating shallow clones. Should we add it?

It should be a separate feature... I think we leave it for later.
