### ISSUE TITLE
Problem creating a repository

### ISSUE THREAD

**Issue by sigdeletras** [koordinates/kart-qgis-plugin#53]
Hi!

Firstable, contragratulations for the plugin! Its a great contribution for the QGIS users community.

I´m testing the plugin guided by documentation, and when I use the create new repository option, QGIS report me the error message  _"The specified folder already exists"_

![image](https://user-images.githubusercontent.com/4746157/147056482-daf02d87-d25b-4c82-9f59-a8da8ae8b98a.png)

The folder is empty and I don't "init" it before.

Meanwhile, if I create a new repository with command terminal and add it using the Kart plugin there isn´t any problem.

This is the information about by environment.

_Kart Plugin version
1.0.1
QGIS version
3.20.2-Odense
Operating system
Windows 10 10.0.19041
Kart version
Kart v0.10.7, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v8.1.1
» PyGit2 v1.7.0; Libgit2 v1.3.0; Git v2.29.2.windows.1
» SQLAlchemy v1.4.11; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.0; Libpq v11.0.9
» SpatialIndex v1.9.3_

Thx

**Comment by volaya** [comment]
Thanks for the bug report!

I fixed it. Now it will check whether the folder is empty or not, and if it exists but it's empty, it will let you create the new repository.

thanks again!

**Comment by greg-alliger** [comment]
Curious if there is a new plugin version with this fix? I am experiencing this as well.

**Comment by rcoup** [comment]
@greg-alliger you can grab a `kart_package` artifact ZIP from https://github.com/koordinates/kart-qgis-plugin/actions/workflows/build.yml?query=branch%3Amain+is%3Asuccess and install it manually via _Plugins... Manage & Install Plugins... Install from ZIP..._

A new release should happen in the next few days though.

**Comment by sigdeletras** [comment]
It's true. After receiving Victor's reply, I did the tests using the plugin installation using zip downloaded from the GitHub repository.
