### ISSUE TITLE
Show more info for commits in log window

### ISSUE THREAD

**Issue by volaya** [koordinates/kart-qgis-plugin#6]
Add info about features added/removed/modified, etc

**Comment by volaya** [comment]
@rcoup @hamishcampbell  I am starting to take a look at this issue, but I haven't been able to find a way of getting just the info about modified features and  layers affected by the commit. Is that a missing functionality?

The --only-feature-count option returns a single number, which i guess is not very informative in this case.

Not sure if this kind of quick summary output is feasible, but I think it would be very interesting, and I remember seeing something like that in the commit info shown in the web version...

**Comment by volaya** [comment]
Right, but that doesnt give you the separate counts for deleted/added/modifed. Just a single number with all those 3 values added together

**Comment by UberMouse** [comment]
Kart doesn't provide that information split up. The web/app display of that information is done by counting features by type returned by the diff

**Comment by volaya** [comment]
ah, ok. Got it. Thanks!
