### ISSUE TITLE
Can't load datasets from PostGIS working copy

### ISSUE THREAD

**Issue by SrNetoChan** [koordinates/kart-qgis-plugin#63]
**Describe the bug**
I have imported datasets into my repository (a localhost postgis working copy), using both the command line and the plugin, but I can't load it into QGIS using the Add to QGIS project option.

2022-05-04T01:44:23     WARNING    Traceback (most recent call last):
              File "C:\Users/testing/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\dockwidget.py", line 158, in wrapper
              f(*args)
              File "C:\Users/testing/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\gui\dockwidget.py", line 734, in addToProject
              layer = self.repo.workingCopyLayer(self.name)
              File "C:\Users/testing/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kart\kartapi.py", line 738, in workingCopyLayer
              uri.setConnection(host, port, database)
             TypeError: QgsDataSourceUri.setConnection(): arguments did not match any overloaded call:
              overload 1: not enough arguments
              overload 2: not enough arguments

I am using a Windows 10 virtual machine, with QGIS 3.22.6 and PostgreSQL 13.6 Postgis 3.1

I am able to load the layers manually, though.

The same type of error appears when I try to show changes on the working copy dataset. I am able to see the attributes changes, but the geometries changes appear empty and a similar error is shown.

**Version info (this is important!):**
 - Operating System (e.g. Windows 10, macOS):  Windows 10

Kart Plugin version
1.0.2
QGIS version
3.22.6-Białowieża
Operating system
Windows 10 10.0.19044
Kart version
Kart v0.11.1, Copyright (c) Kart Contributors
» GDAL v3.3.2; PROJ v8.1.1
» PyGit2 v1.9.0; Libgit2 v1.4.2; Git v2.34.0.windows.1.13.g93318cbc8d
» SQLAlchemy v1.4.29; pysqlite3 v2.6.0/v3.31.1; SpatiaLite v5.0.0; Libpq v11.0.9
» SpatialIndex v1.9.3

  ```
Paste the contents from "Plugins...Kart...About Kart" into here
```

**Comment by SrNetoChan** [comment]
If used a geopackage working copy, this problem can't be reproduced.

**Comment by dzulfiqar-fawwaz** [comment]
Hi everyone! I'm getting similar error (as attached) even after I modified just as what you changed above. I also add str() function to the "port", because it is said that argument 2 has unexpected type 'int'. Is there anything wrong with my code or configuration? Thank you in advance

"
File "C:\Users/dzulfiqar.fawwaz/AppData/Roaming/QGIS/QGIS3\profiles\dzulfiqarfawwaz/python/plugins\kart\kartapi.py", line 740, in workingCopyLayer
              port = str(parse.port) or "5432"
             TypeError: QgsDataSourceUri.setConnection(): arguments did not match any overloaded call:
              overload 1: argument 2 has unexpected type 'int'
              overload 2: argument 2 has unexpected type 'int'
"

**Comment by VicentGN** [comment]
A possible solution for this error: https://github.com/koordinates/kart-qgis-plugin/pull/90
