### ISSUE TITLE
Make the geometry tab sticky in Diff viewer

### ISSUE THREAD

**Issue by SrNetoChan** [koordinates/kart-qgis-plugin#65]
**Is your feature request related to a problem? Please describe.**
1. When using the diff viewer, often you want to check the same attributes or geometries in several changed features. Having the dialog go back to the attributes tab every time you click a new feature makes it tiering to inspect several geometries with a fast glimpse.
2. Same deal 

**Describe the solution you'd like**
It would be nice if the attributes and geometries tabs get "sticky" between features. That is, if you are checking the geometry of a feature, and then click a new feature, the geometry tab should be presented and not going always back to the attributes tab.

**Comment by rcoup** [comment]
@SrNetoChan this will be in the next release. Download a build from "Actions" and you can try it out now.

**Comment by SrNetoChan** [comment]
Thanks @rcoup !! I will give it a try.
