### ISSUE TITLE
Can't load datasets from PostGIS working copy

### ISSUE THREAD

**Issue by VicentGN** [koordinates/kart-qgis-plugin#91]
Related to this one: https://github.com/koordinates/kart-qgis-plugin/issues/63

The problem is the URL parsing process returns the port as a `Integer` which is not allowed by 
`QgsDataSourceUri.setConnection()`

Port is parsed as a `String` now. 

PR: https://github.com/koordinates/kart-qgis-plugin/pull/90

**Comment by olsen232** [comment]
Fixed by #90
